// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package site

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/vladanan/prosto/src/controllers/i18n"
	"github.com/vladanan/prosto/src/models"
	"github.com/vladanan/prosto/src/views"
	"github.com/vladanan/prosto/src/views/cp"
	"log"
	"net/http"
)

func signedin(r *http.Request) string {
	key := i18n.SessionKey("session")
	session, err := i18n.GetSessionFromContext(r.Context(), key)
	if err != nil {
		// http.Error(w, err.Error(), http.StatusInternalServerError)
		// return
		log.Println("dokumentacija: Error on get store:", err)
	}

	auth := session.Values["authenticated"]

	return fmt.Sprint(auth)
}

func getMail(r *http.Request) string {
	key := i18n.SessionKey("session")
	session, err := i18n.GetSessionFromContext(r.Context(), key)
	if err != nil {
		// http.Error(w, err.Error(), http.StatusInternalServerError)
		// return
		log.Println("dokumentacija: Error on get store:", err)
	}

	email := session.Values["user_email"]

	return fmt.Sprint(email)
}

func Pausal(r *http.Request) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			if signedin(r) == "true" && getMail(r) != "y.emailbox-proba@yahoo.com" {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"m-5 text-sm\"><p class=\"text-lg font-bold\">Formulari za pausal su u izradi....</p><br><p class=\"text-blue-700\">Izrada fakture</p><p class=\"text-blue-700\">Pregled KPO</p><p class=\"text-blue-700\">Zurnal</p><p class=\"text-green-700\">Parametri testa samostalnosti</p><p class=\"text-blue-700\">Podešavanje obavestenja</p><p class=\"text-violet-700\"><a href=\"/dashboard\">Podešavanja korisničkog naloga</a></p></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = cp.Sign_in(r, models.SignInFormData{}, "").Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = views.Layout(r).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
