// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package site

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/vladanan/prosto/src/views"
	"net/http"
	// "encoding/json"
	// "fmt"

	"github.com/vladanan/prosto/src/models"
)

// type Note struct {
// 	B_id        int    `db:"b_id"`
// 	Ime_tag     string `db:"ime_tag"`
// 	Mejl        string `db:"mejl"`
// 	Tema        string `db:"tema"`
// 	Poruka      string `db:"poruka"`
// 	User_id     string `db:"user_id"`
// 	User_mail   string `db:"user_mail"`
// 	From_url    string `db:"from_url"`
// 	Datum_upisa any    `db:"datum_upisa"`
// }

// func to_struct (notes []byte) []Note {
//   var p []Note
// 	err := json.Unmarshal(notes, &p)
//   if err != nil {
//     fmt.Printf("Json error: %v", err)
//   }
//   return p
// }

func reverser(notes []models.Note) []models.Note {
	var structLength int
	var newNotes []models.Note
	for i := range notes {
		structLength = i
	}
	for j := structLength; j > -1; j-- {
		newNotes = append(newNotes, notes[j])
	}
	return newNotes
}

func UserPortal(r *http.Request, notes []models.Note) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"m-5 text-blue-700 font-bold text-3xl\">Notes, FAQ, contact </p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if views.GetUserMode(r) == "admin" {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("    ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" <div class=\"m-5 text-slate-500\"><p class=\"text-xl\">Najčešće postavljana pitanja</p><br><br><p>Za sva pitanja pišite na: y.emailbox-vezbamo@yahoo.com    </p><p></p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = views.Layout(r).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
